package com.ws.test.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "TestServiceDelegate", targetNamespace = "http://test.ws.com/")
public interface TestServiceDelegate {

	/**
	 * 
	 * @param arg0
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "test", targetNamespace = "http://test.ws.com/", className = "com.ws.test.client.Test")
	@ResponseWrapper(localName = "testResponse", targetNamespace = "http://test.ws.com/", className = "com.ws.test.client.TestResponse")
	public String test(
			@WebParam(name = "arg0", targetNamespace = "") String arg0);

}
