
package com.sy.cxf.client;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.2.2
 * Mon Jul 11 17:09:19 CST 2016
 * Generated source version: 2.2.2
 * 
 */
 
public class HelloWorld_HelloWorldImplPort_Server{

    protected HelloWorld_HelloWorldImplPort_Server() throws Exception {
        System.out.println("Starting Server");
        Object implementor = new HelloWorldImpl();
        String address = "http://localhost:8080/CxfDemo/webservice/helloWorld";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws Exception { 
        new HelloWorld_HelloWorldImplPort_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
