package com.sy.cxf.client;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.ArrayList;

import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 2.7.12
 * 2014-08-04T22:45:09.609+08:00
 * Generated source version: 2.7.12
 * 
 */
public final class HelloWorld_HelloWorldImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://server.hsy.com/", "HelloWorld");

    private HelloWorld_HelloWorldImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = HelloWorld_Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        HelloWorld_Service ss = new HelloWorld_Service(wsdlURL, SERVICE_NAME);
        HelloWorld port = ss.getHelloWorldImplPort();  
        
        {
        System.out.println("Invoking sayHi...");
        java.lang.String _sayHi_text = "张三";
        java.lang.String _sayHi__return = port.sayHi(_sayHi_text);
        System.out.println("sayHi.result=" + _sayHi__return);


        }
        {
        System.out.println("Invoking sayHiToUser...");
        com.sy.cxf.client.User _sayHiToUser_arg0 = new User();
        _sayHiToUser_arg0.setDescription("王明本人");
        _sayHiToUser_arg0.setName("王明");
        java.lang.String _sayHiToUser__return = port.sayHiToUser(_sayHiToUser_arg0);
        System.out.println("sayHiToUser.result=" + _sayHiToUser__return);


        }
        {
        System.out.println("Invoking sayHiToUserList...");
        java.util.List<com.sy.cxf.client.User> _sayHiToUserList_arg0 = new ArrayList<User>();
        User user1 = new User();
        user1.setDescription("马三立本人");
        user1.setName("马三立");
        _sayHiToUserList_arg0.add(user1);
        User user2 = new User();
        user2.setDescription("郭德纲本人");
        user2.setName("郭德纲");
        _sayHiToUserList_arg0.add(user2);
        java.util.List<java.lang.String> _sayHiToUserList__return = port.sayHiToUserList(_sayHiToUserList_arg0);
        System.out.println("sayHiToUserList.result=" + _sayHiToUserList__return);


        }

        System.exit(0);
    }

}
