
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.sy.cxf.client;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.2
 * Mon Jul 11 17:09:19 CST 2016
 * Generated source version: 2.2.2
 * 
 */

@javax.jws.WebService(
                      serviceName = "HelloWorld",
                      portName = "HelloWorldImplPort",
                      targetNamespace = "http://server.hsy.com/",
                      wsdlLocation = "http://localhost:8080/CxfDemo/webservice/helloWorld?wsdl",
                      endpointInterface = "com.sy.cxf.client.HelloWorld")
                      
public class HelloWorldImpl implements HelloWorld {

    private static final Logger LOG = Logger.getLogger(HelloWorldImpl.class.getName());

    /* (non-Javadoc)
     * @see com.sy.cxf.client.HelloWorld#sayHi(java.lang.String  text )*
     */
    public java.lang.String sayHi(java.lang.String text) { 
        LOG.info("Executing operation sayHi");
        System.out.println(text);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.sy.cxf.client.HelloWorld#sayHiToUser(com.sy.cxf.client.User  arg0 )*
     */
    public java.lang.String sayHiToUser(com.sy.cxf.client.User arg0) { 
        LOG.info("Executing operation sayHiToUser");
        System.out.println(arg0);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.sy.cxf.client.HelloWorld#sayHiToUserList(java.util.List<com.sy.cxf.client.User>  arg0 )*
     */
    public java.util.List<java.lang.String> sayHiToUserList(java.util.List<com.sy.cxf.client.User> arg0) { 
        LOG.info("Executing operation sayHiToUserList");
        System.out.println(arg0);
        try {
            java.util.List<java.lang.String> _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
