
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.ctvit.vdp.client;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.jws.soap.SOAPBinding.ParameterStyle;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.2.2
 * Tue Jul 12 13:27:40 CST 2016
 * Generated source version: 2.2.2
 * 
 */

@javax.jws.WebService(
                      serviceName = "VDPService",
                      portName = "VDPServicePort",
                      targetNamespace = "http://com/ctvit/vdp/ws",
                      wsdlLocation = "http://58.68.243.221:8080/ctvitvdp/services/VDPService?wsdl",
                      endpointInterface = "com.ctvit.vdp.client.VDPPort")
                      
public class VDPPortImpl implements VDPPort {

    private static final Logger LOG = Logger.getLogger(VDPPortImpl.class.getName());

    /* (non-Javadoc)
     * @see com.ctvit.vdp.client.VDPPort#sysEPG(com.ctvit.vdp.client.SynEPGRequest  synEPGRequest )*
     */
    public com.ctvit.vdp.client.SynEPGResponse sysEPG(SynEPGRequest synEPGRequest) { 
        LOG.info("Executing operation sysEPG");
        System.out.println(synEPGRequest);
        try {
            com.ctvit.vdp.client.SynEPGResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.ctvit.vdp.client.VDPPort#sysChannelSection(com.ctvit.vdp.client.SysChannelSectionRequest  sysChannelSectionRequest )*
     */
    public com.ctvit.vdp.client.SysChannelSectionResponse sysChannelSection(SysChannelSectionRequest sysChannelSectionRequest) { 
        LOG.info("Executing operation sysChannelSection");
        System.out.println(sysChannelSectionRequest);
        try {
            com.ctvit.vdp.client.SysChannelSectionResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.ctvit.vdp.client.VDPPort#sysUsers(com.ctvit.vdp.client.SynUsers  sysUsersRequest )*
     */
    public com.ctvit.vdp.client.SynUsersResponse sysUsers(SynUsers sysUsersRequest) { 
        LOG.info("Executing operation sysUsers");
        System.out.println(sysUsersRequest);
        try {
            com.ctvit.vdp.client.SynUsersResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.ctvit.vdp.client.VDPPort#searchProduct(com.ctvit.vdp.client.SearchProductRequest  searchProductRequest )*
     */
    public com.ctvit.vdp.client.SearchProductResponse searchProduct(SearchProductRequest searchProductRequest) { 
        LOG.info("Executing operation searchProduct");
        System.out.println(searchProductRequest);
        try {
            com.ctvit.vdp.client.SearchProductResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.ctvit.vdp.client.VDPPort#synSortTree(com.ctvit.vdp.client.SynSortTreeRequest  synSortTreeRequest )*
     */
    public com.ctvit.vdp.client.SynSortTreeRespose synSortTree(SynSortTreeRequest synSortTreeRequest) { 
        LOG.info("Executing operation synSortTree");
        System.out.println(synSortTreeRequest);
        try {
            com.ctvit.vdp.client.SynSortTreeRespose _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.ctvit.vdp.client.VDPPort#sysOrganization(com.ctvit.vdp.client.SynOrganization  sysOrganizationRequest )*
     */
    public com.ctvit.vdp.client.SynOrganizationResponse sysOrganization(SynOrganization sysOrganizationRequest) { 
        LOG.info("Executing operation sysOrganization");
        System.out.println(sysOrganizationRequest);
        try {
            com.ctvit.vdp.client.SynOrganizationResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.ctvit.vdp.client.VDPPort#achieveMaterial(com.ctvit.vdp.client.AchieveMaterialRequest  achieveMaterialRequest )*
     */
    public com.ctvit.vdp.client.AchieveMaterialResponse achieveMaterial(AchieveMaterialRequest achieveMaterialRequest) { 
        LOG.info("Executing operation achieveMaterial");
        System.out.println(achieveMaterialRequest);
        try {
            com.ctvit.vdp.client.AchieveMaterialResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.ctvit.vdp.client.VDPPort#importProduct(com.ctvit.vdp.client.ImportProductRequest  importProductRequest )*
     */
    public com.ctvit.vdp.client.ImportProductResponse importProduct(ImportProductRequest importProductRequest) { 
        LOG.info("Executing operation importProduct");
        System.out.println(importProductRequest);
        try {
            com.ctvit.vdp.client.ImportProductResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
