
package com.ctvit.vdp.client;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.2.2
 * Tue Jul 12 13:27:40 CST 2016
 * Generated source version: 2.2.2
 * 
 */
 
public class VDPPort_VDPServicePort_Server{

    protected VDPPort_VDPServicePort_Server() throws Exception {
        System.out.println("Starting Server");
        Object implementor = new VDPPortImpl();
        String address = "http://58.68.243.221:8080/ctvitvdp/services/VDPService";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws Exception { 
        new VDPPort_VDPServicePort_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
