package com.ctvit.vdp.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.jws.soap.SOAPBinding.ParameterStyle;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.2.2
 * Tue Jul 12 13:27:40 CST 2016
 * Generated source version: 2.2.2
 * 
 */
 
@WebService(targetNamespace = "http://com/ctvit/vdp/ws", name = "VDPPort")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface VDPPort {

    @WebResult(name = "synEPGResponse", targetNamespace = "http://com/ctvit/vdp/ws/parameter/", partName = "synEPGResponse")
    @WebMethod(action = "sysEPG")
    public SynEPGResponse sysEPG(
        @WebParam(partName = "synEPGRequest", name = "synEPGRequest", targetNamespace = "http://com/ctvit/vdp/ws/parameter/")
        SynEPGRequest synEPGRequest
    );

    @WebResult(name = "sysChannelSectionResponse", targetNamespace = "http://com/ctvit/vdp/ws/parameter/", partName = "sysChannelSectionResponse")
    @WebMethod(action = "sysChannelSection")
    public SysChannelSectionResponse sysChannelSection(
        @WebParam(partName = "sysChannelSectionRequest", name = "sysChannelSectionRequest", targetNamespace = "http://com/ctvit/vdp/ws/parameter/")
        SysChannelSectionRequest sysChannelSectionRequest
    );

    @WebResult(name = "synUsersResponse", targetNamespace = "http://com/ctvit/vdp/ws/parameter/", partName = "synUsersResponse")
    @WebMethod(action = "sysUsers")
    public SynUsersResponse sysUsers(
        @WebParam(partName = "sysUsersRequest", name = "synUsers", targetNamespace = "http://com/ctvit/vdp/ws/parameter/")
        SynUsers sysUsersRequest
    );

    @WebResult(name = "searchProductResponse", targetNamespace = "http://com/ctvit/vdp/ws/parameter/", partName = "searchProductResponse")
    @WebMethod(action = "searchProduct")
    public SearchProductResponse searchProduct(
        @WebParam(partName = "SearchProductRequest", name = "searchProductRequest", targetNamespace = "http://com/ctvit/vdp/ws/parameter/")
        SearchProductRequest searchProductRequest
    );

    @WebResult(name = "synSortTreeRespose", targetNamespace = "http://com/ctvit/vdp/ws/parameter/", partName = "synSortTreeRespose")
    @WebMethod(action = "synSortTree")
    public SynSortTreeRespose synSortTree(
        @WebParam(partName = "synSortTreeRequest", name = "synSortTreeRequest", targetNamespace = "http://com/ctvit/vdp/ws/parameter/")
        SynSortTreeRequest synSortTreeRequest
    );

    @WebResult(name = "synOrganizationResponse", targetNamespace = "http://com/ctvit/vdp/ws/parameter/", partName = "synOrganizationResponse")
    @WebMethod(action = "sysOrganization")
    public SynOrganizationResponse sysOrganization(
        @WebParam(partName = "sysOrganizationRequest", name = "synOrganization", targetNamespace = "http://com/ctvit/vdp/ws/parameter/")
        SynOrganization sysOrganizationRequest
    );

    @WebResult(name = "achieveMaterialResponse", targetNamespace = "http://com/ctvit/vdp/ws/parameter/", partName = "achieveMaterialResponse")
    @WebMethod(action = "achieveMaterial")
    public AchieveMaterialResponse achieveMaterial(
        @WebParam(partName = "AchieveMaterialRequest", name = "achieveMaterialRequest", targetNamespace = "http://com/ctvit/vdp/ws/parameter/")
        AchieveMaterialRequest achieveMaterialRequest
    );

    @WebResult(name = "importProductResponse", targetNamespace = "http://com/ctvit/vdp/ws/parameter/", partName = "importProductResponse")
    @WebMethod(action = "importProduct")
    public ImportProductResponse importProduct(
        @WebParam(partName = "importProductRequest", name = "importProductRequest", targetNamespace = "http://com/ctvit/vdp/ws/parameter/")
        ImportProductRequest importProductRequest
    );
}
