
package com.ctvit.vdp.client;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.jws.soap.SOAPBinding.ParameterStyle;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.2.2
 * Tue Jul 12 13:27:40 CST 2016
 * Generated source version: 2.2.2
 * 
 */

public final class VDPPort_VDPServicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://com/ctvit/vdp/ws", "VDPService");

    private VDPPort_VDPServicePort_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = VDPService.WSDL_LOCATION;
        if (args.length > 0) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        VDPService ss = new VDPService(wsdlURL, SERVICE_NAME);
        VDPPort port = ss.getVDPServicePort(); 
        VDPPort port1=ss.getVDPServicePort();
        
        {
        System.out.println("Invoking sysEPG...");
        com.ctvit.vdp.client.SynEPGRequest _sysEPG_synEPGRequest = null;
        com.ctvit.vdp.client.SynEPGResponse _sysEPG__return = port.sysEPG(_sysEPG_synEPGRequest);
        System.out.println("sysEPG.result=" + _sysEPG__return);


        }
        {
        System.out.println("Invoking sysChannelSection...");
        com.ctvit.vdp.client.SysChannelSectionRequest _sysChannelSection_sysChannelSectionRequest = null;
        com.ctvit.vdp.client.SysChannelSectionResponse _sysChannelSection__return = port.sysChannelSection(_sysChannelSection_sysChannelSectionRequest);
        System.out.println("sysChannelSection.result=" + _sysChannelSection__return);


        }
        {
        System.out.println("Invoking sysUsers...");
        com.ctvit.vdp.client.SynUsers _sysUsers_sysUsersRequest = null;
        com.ctvit.vdp.client.SynUsersResponse _sysUsers__return = port.sysUsers(_sysUsers_sysUsersRequest);
        System.out.println("sysUsers.result=" + _sysUsers__return);


        }
        {
        System.out.println("Invoking searchProduct...");
        com.ctvit.vdp.client.SearchProductRequest _searchProduct_searchProductRequest = null;
        com.ctvit.vdp.client.SearchProductResponse _searchProduct__return = port.searchProduct(_searchProduct_searchProductRequest);
        System.out.println("searchProduct.result=" + _searchProduct__return);


        }
        {
        System.out.println("Invoking synSortTree...");
        com.ctvit.vdp.client.SynSortTreeRequest _synSortTree_synSortTreeRequest = null;
        com.ctvit.vdp.client.SynSortTreeRespose _synSortTree__return = port.synSortTree(_synSortTree_synSortTreeRequest);
        System.out.println("synSortTree.result=" + _synSortTree__return);


        }
        {
        System.out.println("Invoking sysOrganization...");
        com.ctvit.vdp.client.SynOrganization _sysOrganization_sysOrganizationRequest = null;
        com.ctvit.vdp.client.SynOrganizationResponse _sysOrganization__return = port.sysOrganization(_sysOrganization_sysOrganizationRequest);
        System.out.println("sysOrganization.result=" + _sysOrganization__return);


        }
        {
        System.out.println("Invoking achieveMaterial...");
        com.ctvit.vdp.client.AchieveMaterialRequest _achieveMaterial_achieveMaterialRequest = null;
        com.ctvit.vdp.client.AchieveMaterialResponse _achieveMaterial__return = port.achieveMaterial(_achieveMaterial_achieveMaterialRequest);
        System.out.println("achieveMaterial.result=" + _achieveMaterial__return);


        }
        {
        System.out.println("Invoking importProduct...");
        com.ctvit.vdp.client.ImportProductRequest _importProduct_importProductRequest = null;
        com.ctvit.vdp.client.ImportProductResponse _importProduct__return = port.importProduct(_importProduct_importProductRequest);
        System.out.println("importProduct.result=" + _importProduct__return);


        }

        System.exit(0);
    }

}
