
/*
 * 
 */

package com.ctvit.vdp.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.2.2
 * Tue Jul 12 13:27:40 CST 2016
 * Generated source version: 2.2.2
 * 
 */


@WebServiceClient(name = "VDPService", 
                  wsdlLocation = "http://58.68.243.221:8080/ctvitvdp/services/VDPService?wsdl",
                  targetNamespace = "http://com/ctvit/vdp/ws") 
public class VDPService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://com/ctvit/vdp/ws", "VDPService");
    public final static QName VDPServicePort = new QName("http://com/ctvit/vdp/ws", "VDPServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://58.68.243.221:8080/ctvitvdp/services/VDPService?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://58.68.243.221:8080/ctvitvdp/services/VDPService?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public VDPService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public VDPService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public VDPService() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns VDPPort
     */
    @WebEndpoint(name = "VDPServicePort")
    public VDPPort getVDPServicePort() {
        return super.getPort(VDPServicePort, VDPPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns VDPPort
     */
    @WebEndpoint(name = "VDPServicePort")
    public VDPPort getVDPServicePort(WebServiceFeature... features) {
        return super.getPort(VDPServicePort, VDPPort.class, features);
    }

}
